name: Build APK

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Buildozer
        run: pip install buildozer

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: ./bin
